export {default as Hero} from "@/shared/common/Hero/Hero"
export {default as Footer} from "@/shared/common/footer/Footer"
export {default as Header} from "@/shared/common/header/Header"
export {default as SearchBar} from "@/shared/common/searchbar/SearchBar"
export {default as LoadingSpinner} from "@/shared/common/loading/LoadingSpinner"
export {default as DashboardNavbar} from "@/shared/common/dashboard/DashboardNavbar"
export {default as DashboardSidebar} from "@/shared/common/dashboard/DashboardSidebar"