### get all users
GET http://localhost:9000/api/v1/user/get-all-user HTTP/1.1

### create user 
POST http://localhost:9000/api/v1/user/create-user HTTP/1.1
Content-Type: application/json

{
  "name": "ppp",
  "email": "ppp@example.com",
  "password": "123456789"
}

#### testing api
GET http://localhost:9000/api/v1/test HTTP/1.1

### get all products
GET http://localhost:9000/api/v1/product/get-all-product HTTP/1.1

### create product
POST http://localhost:9000/api/v1/product/create-product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI5ZTFhNmFlMGI3MDYxZDMwNDUzN2MiLCJlbWFpbCI6ImNoYXNlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU3MDE0MjM3LCJleHAiOjE3NTcxMDA2Mzd9.6g8iVo9rlD56J-gXxbjiLyK7TUFLCg_-vMp8UHcEWfk
content-type: application/json

{
    "name": "sample5",
    "price": 500,
    "description": "sample5 product"
}

### register user
POST http://localhost:9000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Chase Atlantic",
  "email": "chase@example.com",
  "password": "123456789"
}

### login user
POST http://localhost:9000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "chase@example.com",
  "password": "123456789"
}

### logout user
POST http://localhost:9000/api/v1/auth/logout HTTP/1.1